// Code generated by apic. DO NOT EDIT.

package dsm

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

var (
	dataGroup_createConfig = `resource "dsm_group" "example_group" {
  		name = "example_group"
	}
	data "dsm_group" "example_group" {
		name = "${dsm_group.example_group.name}"
	}`
	dataGroup_updateConfig = `data "dsm_group" "example_group" {
  		name = "example_group_updated"
	}`
)

func TestAccDataGroup(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyGroup,
		Steps: []resource.TestStep{
			{
				Config: dataGroup_createConfig,
			},
		},
	})
}
