// Code generated by apic. DO NOT EDIT.

package dsm

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"testing"
)

var (
	dataAwsGroup_createConfig = `resource "dsm_aws_group" "example_aws_group" {
		name = "example_aws_group"
	 	description = "AWs Group Test"
	 	access_key = "test_key"
	 	secret_key = "test_secret"
	}

	data "dsm_aws_group" "example_aws_group" {
		name = "${dsm_aws_group.example_aws_group.name}"
	}`
	dataAwsGroup_updateConfig = `data "dsm_aws_group" "example_aws_group" {
		name = "example_aws_group_updated"
	}`
)

func TestAccDataAwsGroup(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyAwsGroup,
		Steps: []resource.TestStep{
			{
				Config:             dataAwsGroup_createConfig,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}
