// Code generated by apic. DO NOT EDIT.

package dsm

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"testing"
)

var (
	resourceApp_createConfig = `resource "dsm_group" "example_group" {
		name = "example_group"
	}
  
	resource "dsm_app" "example_app" {
		name = "example_app"
	    	default_group = "${dsm_group.example_group.group_id}"
	}`
	resourceApp_updateConfig = `resource "dsm_app" "example_app {
		name = "example_app_updated"
    		default_group = "${dsm_group.example_group.group_id}"
	}`
)

func TestAccResourceApp(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyApp,
		Steps: []resource.TestStep{
			{
				Config: resourceApp_createConfig,
			},
		},
	})
}

func testAccCheckDestroyApp(s *terraform.State) (err error) {
	return err
}
