// Code generated by apic. DO NOT EDIT.

package dsm

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"testing"
)

var (
	resourceAwsGroup_createConfig = `resource "dsm_aws_group" "example_aws_group" {
  		name = "example_aws_group"
  		description = "AWs Group Test"
  		access_key = "test_key"
  		secret_key = "test_secret"
	}`
	resourceAwsGroup_updateConfig = `resource "dsm_aws_group" "example_aws_group" {
  		name = "example_aws_group_updated"
  		description = "AWS Group Test Update"
	}`
)

func TestAccResourceAwsGroup(t *testing.T) {

	resource.Test(t, resource.TestCase{
		Providers:    testAccProviders,
		PreCheck:     func() { testAccPreCheck(t) },
		CheckDestroy: testAccCheckDestroyAwsGroup,
		Steps: []resource.TestStep{
			{
				Config:             resourceAwsGroup_createConfig,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func testAccCheckDestroyAwsGroup(s *terraform.State) (err error) {
	return err
}
